name: Deploy Jenkins on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: -var 'key_name=${{ secrets.AWS_KEY_PAIR_NAME }}'

    - name: Retrieve instance IP
      id: get_ip
      run: echo "::set-output name=instance_ip::$(cat terraform/ip_address.txt)"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Configure Ansible Inventory
      run: |
        echo "[jenkins_servers]" > ansible/hosts.ini
        echo "${{ steps.get_ip.outputs.instance_ip }}" >> ansible/hosts.ini

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/hosts.ini ansible/install_jenkins.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
        ANSIBLE_PRIVATE_KEY_FILE: ${{ secrets.SSH_PRIVATE_KEY }}


