name: Deploy Jenkins on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -var 'key_name=${{ secrets.EC2_SSH_KEY_NAME }}'
      working-directory: terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Apply
      run: terraform apply -auto-approve -var 'key_name=${{ secrets.EC2_SSH_KEY_NAME }}'
      working-directory: terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Retrieve instance IP
      id: get_ip
      run: echo "::set-output name=instance_ip::$(cat terraform/ip_address.txt)"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Configure Ansible Inventory
      run: |
        echo "[jenkins_servers]" > ansible/hosts.ini
        echo "${{ steps.get_ip.outputs.instance_ip }}" >> ansible/hosts.ini

    - name: Create .ssh directory
      run: mkdir -p /home/runner/.ssh

    - name: Add SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' | tee /home/runner/.ssh/id_rsa > /dev/null
        chmod 600 /home/runner/.ssh/id_rsa
      shell: bash

    - name: Debug SSH Key Permissions and Content
      run: |
        ls -la /home/runner/.ssh
        cat /home/runner/.ssh/id_rsa
      shell: bash

    - name: Start SSH Agent and Add Key
      run: |
        eval $(ssh-agent -s)
        ssh-add /home/runner/.ssh/id_rsa
        ssh-add -l
      shell: bash

    - name: Add Known Hosts
      run: ssh-keyscan -H ${{ steps.get_ip.outputs.instance_ip }} >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: |
        ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ steps.get_ip.outputs.instance_ip }} hostname
      shell: bash

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/hosts.ini ansible/install_jenkins.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
        ANSIBLE_PRIVATE_KEY_FILE: /home/runner/.ssh/id_rsa


